### ISSUE TITLE
RuntimeException: Session could not be established

### ISSUE THREAD

**Issue by Gambini19** [espressif/esp-idf-provisioning-android#24] opened 2020-09-14 06:54 UTC
Hi, I tried to send wifi creditales to device, but i get error on  int responseCode = urlConnection.getResponseCode(); error message ( \n not found: size=0 content=...) unexpected end of stream on com.android.okhttp.Address@59e02351

**Comment by khushbushah2302** [comment] 2020-09-14 09:13
HI @Gambini19 ,
Can you give some more details ?

**Comment by Gambini19** [comment] 2020-09-14 09:33
{"name":"US-176CFC","pop":"abcd1234","transport":"softap"} qrcode data
With this data i  E/AddDeviceActivity: Device Connected Event Received
then choose wifi network and get error  E/Espressif::SoftAPTransport: failed to connect to /192.168.4.1 (port 80) from /192.168.254.138 (port 45196) after 5000ms
2020-09-14 14:32:01.417 13844-15086/com.espressif.wifi_provisioning E/Espressif::SoftAPTransport: failed to connect to /192.168.4.1 (port 80) from /192.168.254.138 (port 45196) after 5000ms
2020-09-14 14:32:01.417 13844-15086/com.espressif.wifi_provisioning W/System.err: java.net.SocketTimeoutException: failed to connect to /192.168.4.1 (port 80) from /192.168.254.138 (port 45196) after 5000ms
2020-09-14 14:32:01.418 13844-15086/com.espressif.wifi_provisioning W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
2020-09-14 14:32:01.418 13844-15086/com.espressif.wifi_provisioning W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:129)
2020-09-14 14:32:01.418 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
2020-09-14 14:32:01.418 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.net.Socket.connect(Socket.java:621)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2020-09-14 14:32:01.419 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2020-09-14 14:32:01.420 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2020-09-14 14:32:01.420 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2020-09-14 14:32:01.420 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2020-09-14 14:32:01.420 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
2020-09-14 14:32:01.420 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
2020-09-14 14:32:01.420 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport.sendPostRequest(SoftAPTransport.java:78)
2020-09-14 14:32:01.421 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport.access$000(SoftAPTransport.java:49)
2020-09-14 14:32:01.421 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:125)
2020-09-14 14:32:01.421 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020-09-14 14:32:01.421 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-14 14:32:01.421 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-09-14 14:32:01.421 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-09-14 14:32:01.421 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-09-14 14:32:01.422 13844-15086/com.espressif.wifi_provisioning W/System.err: java.lang.RuntimeException: Error ! Connection Lost
2020-09-14 14:32:01.422 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport.sendPostRequest(SoftAPTransport.java:102)
2020-09-14 14:32:01.422 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport.access$000(SoftAPTransport.java:49)
2020-09-14 14:32:01.423 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:125)
2020-09-14 14:32:01.423 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020-09-14 14:32:01.423 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-14 14:32:01.423 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-09-14 14:32:01.423 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-09-14 14:32:01.423 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-09-14 14:32:01.423 13844-15086/com.espressif.wifi_provisioning D/ESP:ESPDevice: disableOnlyWifiNetwork()
2020-09-14 14:32:01.429 13844-15086/com.espressif.wifi_provisioning W/System.err: java.lang.RuntimeException: Session could not be established
2020-09-14 14:32:01.429 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.Session$1.onSuccess(Session.java:101)
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning W/System.err:     at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:126)
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning D/ESP:ESPDevice: disableOnlyWifiNetwork()
2020-09-14 14:32:01.430 13844-15086/com.espressif.wifi_provisioning E/ESP:ESPDevice: Connectivity Manager is already unregistered

**Comment by khushbushah2302** [comment] 2020-09-14 12:31
@Gambini19 ,
May I know your phone's Android version ? 
and can you try with manual provision (I don't have a QR code option) ?

**Comment by Gambini19** [comment] 2020-09-14 12:44
android redmi note 8t(android 9)
yes i try it(can you try with manual provision (I don't have a QR code option) ?),  the same error

**Comment by khushbushah2302** [comment] 2020-09-17 04:15
Please also give details about device side and the idf version.

**Comment by ArtemDivin** [comment] 2020-09-17 05:40
device based on esp32, version idf 4.0
base project on ios work fine

**Comment by MegaAndroidDeveloper666** [comment] 2020-10-02 07:42
Do you have any thoughts yet?

**Comment by khushbushah2302** [comment] 2020-10-04 14:42
```failed to connect to /192.168.4.1 (port 80) from /192.168.254.138 (port 45196) after 5000ms```
From logs, it seems phone must have switched to some other Wi-Fi network.

**Comment by MegaAndroidDeveloper666** [comment] 2020-10-05 05:13
Well, phone is switching to device Wi-Fi network and then tries to establish session, but fails. Requests to setablish session are going through device hotspot. So it doesn't depend on Wi-Fi network that I'm trying to get device to connect to. :(

**Comment by khushbushah2302** [comment] 2020-10-05 07:13
@MegaAndroidDeveloper666 ,
Can you share your logs ? Because in given logs, the source IP address is of a different subnet, which indicates phone is not connected to device hotspot. 
Have you tried manual provision and facing same error in manual provisioning too ?

**Comment by MegaAndroidDeveloper666** [comment] 2020-10-05 14:43
Actually ArtemDivin and I are both developers on same team so logs are same. We tried to debug lib step by step, but session couldn't establish anyways providing this log

**Comment by khushbushah2302** [comment] 2020-11-06 07:10
@MegaAndroidDeveloper666 ,
We are working on this issue. We will provide fix asap.

**Comment by MegaAndroidDeveloper666** [comment] 2020-11-06 07:18
@khushbushah2302 thanks in advance! Hope it won't spend your free time much

**Comment by khushbushah2302** [comment] 2021-01-29 11:52
Hi @Gambini19 , @MegaAndroidDeveloper666 ,

Sorry for the late reply.
We have fixed session issue for SoftAP transport few days ago.
Please check our latest app and latest firmware.
Let us know if you still face the issue.

**Comment by shahpiyushv** [comment] 2021-02-03 09:36
Closing this issue as appropriate fixes have gone into the phone app as well as the firmware. Please feel free to reopen if you are still facing issues discussed in this thread.

**Closed by shahpiyushv** 2021-02-03 09:36 UTC

**Comment by hivislav** [comment] 2024-10-07 15:57
Hi! The problem is relevant again, both in our application and in the demo application. Tested on Samsung S23 Ultra, Android 14.
Log from demo app:

2024-10-07 17:02:19.077  8207-15492 Espress...ansport com.espressif.wifi_provisioning      E  Failed to connect to /192.168.4.1:80
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  java.net.ConnectException: Failed to connect to /192.168.4.1:80
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
2024-10-07 17:02:19.077  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.transport.SoftAPTransport.sendPostRequest(SoftAPTransport.java:85)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.transport.SoftAPTransport.access$000(SoftAPTransport.java:43)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:143)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.lang.Thread.run(Thread.java:1012)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  java.lang.RuntimeException: Error ! Connection Lost
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.transport.SoftAPTransport.sendPostRequest(SoftAPTransport.java:120)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.transport.SoftAPTransport.access$000(SoftAPTransport.java:43)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:143)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024-10-07 17:02:19.078  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.lang.Thread.run(Thread.java:1012)
2024-10-07 17:02:19.078  8207-15492 ESP:ESPDevice     com.espressif.wifi_provisioning      D  disableOnlyWifiNetwork()
2024-10-07 17:02:19.082  8207-15492 Connect...Manager com.espressif.wifi_provisioning      D  StackLog: [android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:5199)] [com.espressif.provisioning.ESPDevice.disableOnlyWifiNetwork(ESPDevice.java:1564)] [com.espressif.provisioning.ESPDevice.access$1000(ESPDevice.java:72)] [com.espressif.provisioning.ESPDevice$18.onFailure(ESPDevice.java:1168)] [com.espressif.provisioning.Session$2.onFailure(Session.java:141)] [com.espressif.provisioning.transport.SoftAPTransport.sendPostRequest(SoftAPTransport.java:120)] [com.espressif.provisioning.transport.SoftAPTransport.access$000(SoftAPTransport.java:43)] [com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:143)] [java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)] [java.util.concurrent.FutureTask.run(FutureTask.java:264)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)] [java.lang.Thread.run(Thread.java:1012)]
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  java.lang.IllegalArgumentException: Null input buffer
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at javax.crypto.Cipher.update(Cipher.java:1694)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.security.Security1.decrypt(Security1.java:208)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.Session$2.onSuccess(Session.java:131)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:144)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024-10-07 17:02:19.083  8207-15492 System.err        com.espressif.wifi_provisioning      W  	at java.lang.Thread.run(Thread.java:1012)
2024-10-07 17:02:19.083  8207-15492 ESP:ESPDevice     com.espressif.wifi_provisioning      D  disableOnlyWifiNetwork()
2024-10-07 17:02:19.083  8207-15492 Connect...Manager com.espressif.wifi_provisioning      D  StackLog: [android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:5199)] [com.espressif.provisioning.ESPDevice.disableOnlyWifiNetwork(ESPDevice.java:1564)] [com.espressif.provisioning.ESPDevice.access$1000(ESPDevice.java:72)] [com.espressif.provisioning.ESPDevice$18.onFailure(ESPDevice.java:1168)] [com.espressif.provisioning.Session$2.onFailure(Session.java:141)] [com.espressif.provisioning.transport.SoftAPTransport$1.run(SoftAPTransport.java:146)] [java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)] [java.util.concurrent.FutureTask.run(FutureTask.java:264)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)] [java.lang.Thread.run(Thread.java:1012)]
2024-10-07 17:02:19.083  8207-15492 Connect...Manager com.espressif.wifi_provisioning      D  NetworkCallback was already unregistered
