### ISSUE TITLE
Scan Networks 

### ISSUE THREAD

**Issue by gonbooster** [espressif/esp-idf-provisioning-android#28] opened 2020-10-23 12:07 UTC
Hi, testing Esp Soaftp 2.1 (https://play.google.com/store/apps/details?id=com.espressif.provsoftap&hl=es_VE)
withouth QR code doesn't  list home Networks.
Tested in Xiaomi Redmi 8 (A10) and in A8.1

**Comment by khushbushah2302** [comment] 2020-10-28 09:31
@gonbooster ,
In WiFi list screen, please check if phone is connected to SoftAP device or not.
Can you please share Android app logs ?

**Comment by gonbooster** [comment] 2020-10-28 09:40
Hi. Yes, is connected succesfully to SoftAp.

`2020-10-28 10:35:08.197 18438-18649/com.nts.teka.tekahomeandroid.debug V/FA: Activity paused, time: 2623376
2020-10-28 10:35:08.262 18438-18649/com.nts.teka.tekahomeandroid.debug V/FA: Connection attempt already in progress
2020-10-28 10:35:08.266 18438-18649/com.nts.teka.tekahomeandroid.debug D/FA: Connected to remote service
2020-10-28 10:35:08.268 18438-18649/com.nts.teka.tekahomeandroid.debug V/FA: Processing queued up service tasks: 2
2020-10-28 10:35:10.203 18438-18649/com.nts.teka.tekahomeandroid.debug D/FA: Application going to the background
2020-10-28 10:35:15.289 18438-18649/com.nts.teka.tekahomeandroid.debug V/FA: Inactivity, disconnecting from the service
2020-10-28 10:35:48.410 18438-18518/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: enableOnlyWifiNetwork()
2020-10-28 10:35:48.425 18438-18792/com.nts.teka.tekahomeandroid.debug V/FA: Activity resumed, time: 2663642
2020-10-28 10:35:48.460 18438-18518/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Network is available - 3
2020-10-28 10:35:48.467 18438-18792/com.nts.teka.tekahomeandroid.debug V/FA: Connecting to remote service
2020-10-28 10:35:48.545 18438-18438/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Send Wi-Fi scan command to device
2020-10-28 10:35:48.946 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.946 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.946 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->copyMemory(JJJ)V (greylist, linking, allowed)
2020-10-28 10:35:48.947 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.947 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getByte(J)B (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.947 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getByte(Ljava/lang/Object;J)B (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.947 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(J)J (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.947 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->putByte(JB)V (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.947 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->putByte(Ljava/lang/Object;JB)V (greylist,core-platform-api, linking, allowed)
2020-10-28 10:35:48.947 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
2020-10-28 10:35:48.948 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
2020-10-28 10:35:48.948 18438-18438/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
2020-10-28 10:35:49.044 18438-18438/com.nts.teka.tekahomeandroid.debug W/Looper: Slow Looper main: doFrame is 494ms late because of 1 msg, msg 1 took 509ms (seq=387 running=438ms runnable=5ms io=1ms h=android.os.Handler c=androidx.fragment.app.FragmentManager$4)
2020-10-28 10:35:49.045 18438-18438/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Connecting to device
2020-10-28 10:35:49.114 18438-18792/com.nts.teka.tekahomeandroid.debug D/FA: Connected to remote service
2020-10-28 10:35:49.116 18438-18792/com.nts.teka.tekahomeandroid.debug V/FA: Processing queued up service tasks: 1
2020-10-28 10:35:49.905 18438-18803/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Value : {
    	"prov":	{
    		"ver":	"v1.1",
    		"cap":	["no_pop", "wifi_scan"]
    	}
    }
2020-10-28 10:35:49.906 18438-18803/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Device Version : v1.1
2020-10-28 10:35:49.909 18438-18803/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Returning ssid : TEKA_0202
2020-10-28 10:35:49.909 18438-18803/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Capabilities : [no_pop, wifi_scan]
2020-10-28 10:35:49.912 18438-18803/com.nts.teka.tekahomeandroid.debug D/EventBus: No subscribers registered for event class com.espressif.provisioning.DeviceConnectionEvent
2020-10-28 10:35:49.912 18438-18803/com.nts.teka.tekahomeandroid.debug D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
2020-10-28 10:35:54.123 18438-18792/com.nts.teka.tekahomeandroid.debug V/FA: Inactivity, disconnecting from the service
`

Curiouslly if i add a debug break point in ESPDevice.java  Line 444 ( Log.d(TAG, "Send Wi-Fi scan command to device");)
works like chaman! ..Y thinks is a problem with delay into the library

`2020-10-28 10:39:02.602 19077-19199/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Network is available - 3
2020-10-28 10:39:05.168 19077-19077/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Send Wi-Fi scan command to device
2020-10-28 10:39:05.671 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.671 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.671 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->copyMemory(JJJ)V (greylist, linking, allowed)
2020-10-28 10:39:05.671 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.671 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getByte(J)B (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.671 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getByte(Ljava/lang/Object;J)B (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.671 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(J)J (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.672 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->putByte(JB)V (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.672 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->putByte(Ljava/lang/Object;JB)V (greylist,core-platform-api, linking, allowed)
2020-10-28 10:39:05.672 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
2020-10-28 10:39:05.672 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
2020-10-28 10:39:05.673 19077-19077/com.nts.teka.tekahomeandroid.debug W/meandroid.debu: Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
2020-10-28 10:39:05.692 19077-19077/com.nts.teka.tekahomeandroid.debug W/Looper: Slow Looper main: Long Msg: seq=551 plan=10:39:02.586  late=0ms wall=3100ms running=503ms runnable=2ms h=android.os.Handler c=androidx.fragment.app.FragmentManager$4
2020-10-28 10:39:05.692 19077-19077/com.nts.teka.tekahomeandroid.debug I/Choreographer: Skipped 185 frames!  The application may be doing too much work on its main thread.
2020-10-28 10:39:05.777 19077-19077/com.nts.teka.tekahomeandroid.debug W/Looper: Slow Looper main: doFrame is 3087ms late because of 1 msg, msg 1 took 3100ms (seq=551 running=503ms runnable=2ms h=android.os.Handler c=androidx.fragment.app.FragmentManager$4)
2020-10-28 10:39:05.777 19077-19077/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Connecting to device
2020-10-28 10:39:05.779 19077-19151/com.nts.teka.tekahomeandroid.debug I/OpenGLRenderer: Davey! duration=3173ms; Flags=0, IntendedVsync=2857825765296, Vsync=2860909098506, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=2860914200938, AnimationStart=2860914313594, PerformTraversalsStart=2860914449167, DrawStart=2860987143542, SyncQueued=2860996613854, SyncStart=2860996967083, IssueDrawCommandsStart=2860997055156, SwapBuffers=2860999029219, FrameCompleted=2860999487813, DequeueBufferDuration=119000, QueueBufferDuration=219000, 
2020-10-28 10:39:06.741 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Value : {
    	"prov":	{
    		"ver":	"v1.1",
    		"cap":	["no_pop", "wifi_scan"]
    	}
    }
2020-10-28 10:39:06.742 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Device Version : v1.1
2020-10-28 10:39:06.746 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Returning ssid : TEKA_0202
2020-10-28 10:39:06.746 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Capabilities : [no_pop, wifi_scan]
2020-10-28 10:39:06.748 19077-19377/com.nts.teka.tekahomeandroid.debug D/EventBus: No subscribers registered for event class com.espressif.provisioning.DeviceConnectionEvent
2020-10-28 10:39:06.749 19077-19377/com.nts.teka.tekahomeandroid.debug D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
2020-10-28 10:39:07.554 19077-19144/com.nts.teka.tekahomeandroid.debug V/FA: Inactivity, disconnecting from the service
2020-10-28 10:39:09.118 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Process Wi-Fi start scan command response
2020-10-28 10:39:09.214 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Process Wi-Fi scan status command response
2020-10-28 10:39:09.219 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Total count : 9 and start index is : 0
2020-10-28 10:39:09.219 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Getting 4 SSIDs
2020-10-28 10:39:09.345 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Successfully got SSID list
2020-10-28 10:39:09.362 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Response count : 4
2020-10-28 10:39:09.362 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : MOVISTAR_9053
2020-10-28 10:39:09.364 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 1
2020-10-28 10:39:09.364 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : EUSKALTEL_0BFA
2020-10-28 10:39:09.365 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 2
2020-10-28 10:39:09.366 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : CafeteriaLoramendi
2020-10-28 10:39:09.366 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 3
2020-10-28 10:39:09.367 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : MOVISTAR_9053
2020-10-28 10:39:09.368 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 3
2020-10-28 10:39:09.368 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Total count : 9 and start index is : 4
2020-10-28 10:39:09.368 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Getting 4 SSIDs
2020-10-28 10:39:09.431 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Successfully got SSID list
2020-10-28 10:39:09.441 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Response count : 4
2020-10-28 10:39:09.442 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : _EUSKALTELWIFI_KALEAN
2020-10-28 10:39:09.443 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 4
2020-10-28 10:39:09.443 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : vodafoneBA1320
2020-10-28 10:39:09.444 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 5
2020-10-28 10:39:09.444 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : MOVISTAR_BAB8
2020-10-28 10:39:09.445 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 6
2020-10-28 10:39:09.446 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : MOVISTAR_C9E2
2020-10-28 10:39:09.446 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 7
2020-10-28 10:39:09.446 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Total count : 9 and start index is : 8
2020-10-28 10:39:09.447 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Getting 1 SSIDs
2020-10-28 10:39:09.550 19077-19377/com.nts.teka.tekahomeandroid.debug D/ESP:ESPDevice: Successfully got SSID list
2020-10-28 10:39:09.552 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Response count : 1
2020-10-28 10:39:09.552 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: SSID : MiFibra-A4F3
2020-10-28 10:39:09.553 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Size of  list : 8
2020-10-28 10:39:09.553 19077-19377/com.nts.teka.tekahomeandroid.debug E/ESP:ESPDevice: Wi-Fi LIST Completed
`

**Comment by khushbushah2302** [comment] 2020-10-29 10:32
@gonbooster ,

From above logs, WiFi networks are already received from device like MOVISTAR_9053, EUSKALTEL_0BFA, vodafoneBA1320 etc. So app should display these networks in Wi-Fi scan list screen. 
Is Wi-Fi scan list screen not displaying any network ?

**Comment by gonbooster** [comment] 2020-10-29 12:14
Hi @khushbushah2302 the last log is when it works well.
But for make it working i have to add a debug break point in ESPDevice.java Line 444 ( Log.d(TAG, "Send Wi-Fi scan command to device");)

`something strange happens in provisionManager.getEspDevice().scanNetworks(new WiFiScanListener(){...}

Curiouslly if i add a debug break point in ESPDevice.java Line 444 ( Log.d(TAG, "Send Wi-Fi scan command to device");)
works like chaman!

But if y add it only on ESPProvisionManager.java Line 108 (return espDevice) not work.`

**Comment by afcec** [comment] 2020-11-19 16:46
Hi, I am experiencing exactly the same issue. The networks are not listed with the APP version 2.0.3. On the ESP side I am using ESP-IDF 4.0.1 and wifi_prov_mgr

**Comment by gonbooster** [comment] 2020-11-20 13:28
Solved!

adding next line in Android code

`        espProvisionManager.getEspDevice().setProofOfPossession("");`

before 

`
        espDevice = espProvisionManager.createESPDevice(ESPConstants.TransportType.TRANSPORT_SOFTAP, ESPConstants.SecurityType.SECURITY_1);`

becouse my ESP connection Board have POP set to null

`wifi_prov_security_t security = WIFI_PROV_SECURITY_1;
const char *pop = NULL;
int32_t i32_resultado = wifi_prov_mgr_start_provisioning(security, pop, service_name, service_key);`

**Comment by khushbushah2302** [comment] 2020-11-23 10:01
Hi @gonbooster ,

Thanks for finding the root cause and giving solution.
I will do this change and provide fix in provisioning library very soon.

**Comment by khushbushah2302** [comment] 2020-11-25 10:11
Hi @gonbooster , @afcec 

Fix is available now on GitHub and in Play Store apps.

Thanks.

**Comment by afcec** [comment] 2020-11-25 15:01
Great @khushbushah2302, thanks!

**Comment by shahpiyushv** [comment] 2020-11-26 13:37
Closing this issue as it has been fixed. Please feel free to reopen if required.

**Closed by shahpiyushv** 2020-11-26 13:37 UTC
